name: hydeath
version: '${version}'
main: xyz.hynse.hydeath.Hydeath
api-version: '1.20'
authors: [MidnightTale]
website: hynse.xyz
folia-supported: true
commands:
  hydeathreload:
    description: Reloads the Hydeath configuration
    usage: /hydeathreload
  unlock:
    description: unlock death item to allow can be pickup by other player
    usage: /unlock
  unlocknear:
    description: unlock nearby 10 block death item to allow can be pickup by other player
    usage: /unlocknear <radius>